### ISSUE TITLE
I think it is impolite to remove origin Copyright information on my9291 driver code

### ISSUE THREAD

**Issue by vowstar** [icamgo/noduino-sdk#17]
I think it is impolite to remove origin Copyright information on these code, I support open source but I don't think remove the original copyright information is good idea. 

I'm the the author of the original code, It is no problem add "Copyright (c) 2016 - 2026 MaiKe Labs" if you improve these code, but remove the original information is impolite. You should 
contact me before do these thing.

The my9291 driver code is here
[https://github.com/icamgo/noduino-sdk/commit/8cecdbe97e83c210a3cfdf0e7fb5c2065109fe1f](https://github.com/icamgo/noduino-sdk/commit/8cecdbe97e83c210a3cfdf0e7fb5c2065109fe1f)

**Comment by icamgo** [comment]
check the noduino-sdk/lib/noduino/mjpwm/
